server:
  port: 9999  #启动时端口号冲突
  context-path: /Test   #指定项目名
  jsp-servlet:
    init-parameters:
      development: true  #开启jsp的热部署
spring:
  mvc:
    view:
      prefix: / #配置SpringBoot的视图解析器
      suffix: .jsp

  datasource:
    type: org.apache.commons.dbcp.BasicDataSource #指定连接池类型
    driver-class-name: com.mysql.jdbc.Driver  #指定驱动
                    #mycat所在的主机IP      逻辑库
    url: jdbc:mysql://localhost:3306/novel?characterEncoding=utf-8  #指定url
    username: root  #指定用户名
    password: root  #指定密码
  redis:
    cluster:
     nodes: 192.168.153.19:7000,192.168.153.19:7002,192.168.153.19:7003,192.168.153.19:7004,192.168.153.19:7005,192.168.153.19:7006
mybatis:
  type-aliases-package: com.baizhi.entity #指定起别名的类
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml #指定mapper配置文件的位置

